export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  price: number;
  originalPrice: number;
  image: string;
  badge: "SALE" | "HOT" | "NEW" | null;
  inStock: boolean;
  rating: number;
  reviews: number;
  description: string;
  isOnWebsite: boolean;
  isOnStore: boolean;
}

export const CATEGORIES = [
  "Whey Protein",
  "Pre-Workout",
  "BCAA",
  "Fat Burner",
  "Multivitamins",
  "Creatine",
  "Weight Gainer",
  "Shaker Bottle",
];

export const BRANDS = [
  "Optimum Nutrition",
  "Dymatize",
  "MuscleTech",
  "BSN",
  "USN",
  "MyProtein",
  "Ultimate Nutrition",
  "Isopure",
  "Cellucor",
  "BPI Sports",
];

export const defaultProducts: Product[] = [
  // Whey Protein
  {
    id: "wp-1",
    name: "Gold Standard 100% Whey",
    brand: "Optimum Nutrition",
    category: "Whey Protein",
    price: 14500,
    originalPrice: 17000,
    image: "https://m.media-amazon.com/images/I/71qq7DCcBmL._SL1500_.jpg",
    badge: "SALE",
    inStock: true,
    rating: 4.9,
    reviews: 2840,
    description:
      "The world's best-selling whey protein. 24g protein per serving, low fat, low sugar. Available in multiple delicious flavors.",
    isOnWebsite: true,
    isOnStore: true,
  },
  {
    id: "wp-2",
    name: "Elite Whey Protein",
    brand: "Dymatize",
    category: "Whey Protein",
    price: 12800,
    originalPrice: 15000,
    image: "https://m.media-amazon.com/images/I/71EZMLNdVeL._SL1500_.jpg",
    badge: "SALE",
    inStock: true,
    rating: 4.7,
    reviews: 1520,
    description:
      "25g of ultra-premium protein per serving. Light and fluffy texture with outstanding mixability.",
    isOnWebsite: true,
    isOnStore: true,
  },
  {
    id: "wp-3",
    name: "NitroTech Whey Gold",
    brand: "MuscleTech",
    category: "Whey Protein",
    price: 13200,
    originalPrice: 16000,
    image: "https://m.media-amazon.com/images/I/81gFMlbhysL._SL1500_.jpg",
    badge: "HOT",
    inStock: true,
    rating: 4.8,
    reviews: 980,
    description:
      "Scientifically engineered whey protein with peptides and BCAA blend for rapid absorption.",
    isOnWebsite: false,
    isOnStore: true,
  },
  {
    id: "wp-4",
    name: "Syntha-6 Whey Protein",
    brand: "BSN",
    category: "Whey Protein",
    price: 11500,
    originalPrice: 13500,
    image: "https://m.media-amazon.com/images/I/71ItHqniaoL._SL1500_.jpg",
    badge: "SALE",
    inStock: true,
    rating: 4.6,
    reviews: 765,
    description:
      "Multi-functional protein powder with a sustained release matrix for all-day muscle support.",
    isOnWebsite: false,
    isOnStore: true,
  },
  {
    id: "wp-5",
    name: "Zero Carb Isolean",
    brand: "Isopure",
    category: "Whey Protein",
    price: 16900,
    originalPrice: 20000,
    image: "https://m.media-amazon.com/images/I/61ugKV9Y1AL._SL1500_.jpg",
    badge: "NEW",
    inStock: true,
    rating: 4.8,
    reviews: 430,
    description:
      "100% pure whey protein isolate. Zero carbs, zero fat, lactose-free protein.",
    isOnWebsite: false,
    isOnStore: true,
  },
  // Pre-Workout
  {
    id: "pw-1",
    name: "C4 Original Pre-Workout",
    brand: "Cellucor",
    category: "Pre-Workout",
    price: 6500,
    originalPrice: 8000,
    image: "https://m.media-amazon.com/images/I/71BLUKqJDxL._SL1500_.jpg",
    badge: "HOT",
    inStock: true,
    rating: 4.8,
    reviews: 3200,
    description:
      "America's #1 selling pre-workout. Explosive energy, sharp focus, and powerful pumps.",
    isOnWebsite: true,
    isOnStore: true,
  },
  {
    id: "pw-2",
    name: "Ghost Legend All Out",
    brand: "BSN",
    category: "Pre-Workout",
    price: 7800,
    originalPrice: 9500,
    image: "https://m.media-amazon.com/images/I/61k0V5ZIFSL._SL1500_.jpg",
    badge: "NEW",
    inStock: true,
    rating: 4.7,
    reviews: 890,
    description:
      "Full-transparency label pre-workout with 250mg caffeine, beta-alanine, and citrulline.",
    isOnWebsite: false,
    isOnStore: true,
  },
  {
    id: "pw-3",
    name: "Mr. Hyde Pre-Workout",
    brand: "BPI Sports",
    category: "Pre-Workout",
    price: 5900,
    originalPrice: 7200,
    image: "https://m.media-amazon.com/images/I/71r3h9TGERL._SL1500_.jpg",
    badge: "SALE",
    inStock: true,
    rating: 4.5,
    reviews: 612,
    description:
      "Extended release caffeine matrix delivers energy that lasts your entire workout.",
    isOnWebsite: false,
    isOnStore: true,
  },
  {
    id: "pw-4",
    name: "Bulk Pre-Workout",
    brand: "MyProtein",
    category: "Pre-Workout",
    price: 5200,
    originalPrice: 6500,
    image: "https://m.media-amazon.com/images/I/61fZKD1vJKL._SL1500_.jpg",
    badge: "SALE",
    inStock: true,
    rating: 4.6,
    reviews: 345,
    description:
      "Formulated with 6g citrulline malate and 3.2g beta-alanine for extreme performance.",
    isOnWebsite: false,
    isOnStore: true,
  },
  // BCAA
  {
    id: "bc-1",
    name: "Xtend Original BCAA",
    brand: "BSN",
    category: "BCAA",
    price: 4800,
    originalPrice: 6000,
    image: "https://m.media-amazon.com/images/I/818a-T5DKRL._SL1500_.jpg",
    badge: "HOT",
    inStock: true,
    rating: 4.9,
    reviews: 4100,
    description:
      "7g BCAAs with 2.5g L-Glutamine and electrolytes. Zero calories, zero sugar.",
    isOnWebsite: true,
    isOnStore: true,
  },
  {
    id: "bc-2",
    name: "BCAA Energy",
    brand: "Optimum Nutrition",
    category: "BCAA",
    price: 4200,
    originalPrice: 5200,
    image: "https://m.media-amazon.com/images/I/71c-RCMSaOL._SL1500_.jpg",
    badge: "SALE",
    inStock: true,
    rating: 4.7,
    reviews: 820,
    description:
      "BCAAs plus natural energizers for focus and endurance during any workout.",
    isOnWebsite: false,
    isOnStore: true,
  },
  {
    id: "bc-3",
    name: "Amino Energy EAA+",
    brand: "Dymatize",
    category: "BCAA",
    price: 5500,
    originalPrice: 6800,
    image: "https://m.media-amazon.com/images/I/71bJz3xZjHL._SL1500_.jpg",
    badge: "NEW",
    inStock: true,
    rating: 4.6,
    reviews: 390,
    description:
      "Complete EAA profile with added BCAAs and electrolytes for peak recovery.",
    isOnWebsite: false,
    isOnStore: true,
  },
  // Fat Burner
  {
    id: "fb-1",
    name: "Hydroxycut Hardcore Elite",
    brand: "MuscleTech",
    category: "Fat Burner",
    price: 5200,
    originalPrice: 6500,
    image: "https://m.media-amazon.com/images/I/71LcuRb0KuL._SL1500_.jpg",
    badge: "HOT",
    inStock: true,
    rating: 4.5,
    reviews: 1890,
    description:
      "America's best-selling weight loss supplement brand. Boosts metabolism and energy.",
    isOnWebsite: true,
    isOnStore: true,
  },
  {
    id: "fb-2",
    name: "Lipo-6 Black Intense",
    brand: "USN",
    category: "Fat Burner",
    price: 4800,
    originalPrice: 6000,
    image: "https://m.media-amazon.com/images/I/61V-Q5EMQDL._SL1500_.jpg",
    badge: "SALE",
    inStock: true,
    rating: 4.4,
    reviews: 723,
    description:
      "Ultra-concentrated formula designed to support fat loss and lean muscle retention.",
    isOnWebsite: false,
    isOnStore: true,
  },
  {
    id: "fb-3",
    name: "Burn XT Thermogenic",
    brand: "BPI Sports",
    category: "Fat Burner",
    price: 4200,
    originalPrice: 5500,
    image: "https://m.media-amazon.com/images/I/61mZ0a7NKKL._SL1500_.jpg",
    badge: "NEW",
    inStock: true,
    rating: 4.6,
    reviews: 510,
    description:
      "Clinically-studied ingredients for fat burning, appetite suppression, and energy.",
    isOnWebsite: false,
    isOnStore: true,
  },
  // Multivitamins
  {
    id: "mv-1",
    name: "Opti-Men Multivitamin",
    brand: "Optimum Nutrition",
    category: "Multivitamins",
    price: 5500,
    originalPrice: 7000,
    image: "https://m.media-amazon.com/images/I/81RuBd5EXWL._SL1500_.jpg",
    badge: "HOT",
    inStock: true,
    rating: 4.8,
    reviews: 2100,
    description:
      "75+ active ingredients. Complete vitamin, mineral, and amino complex for men.",
    isOnWebsite: true,
    isOnStore: true,
  },
  {
    id: "mv-2",
    name: "Animal Pak Multivitamin",
    brand: "Ultimate Nutrition",
    category: "Multivitamins",
    price: 6200,
    originalPrice: 7800,
    image: "https://m.media-amazon.com/images/I/41O0mF0YKOL.jpg",
    badge: "SALE",
    inStock: true,
    rating: 4.7,
    reviews: 940,
    description:
      "The ultimate training pack for elite athletes. 11 tablets per serving, 44 packs.",
    isOnWebsite: false,
    isOnStore: true,
  },
  {
    id: "mv-3",
    name: "Daily Vitamins",
    brand: "MyProtein",
    category: "Multivitamins",
    price: 2800,
    originalPrice: 3500,
    image: "https://m.media-amazon.com/images/I/61h9XVy3JkL._SL1500_.jpg",
    badge: "NEW",
    inStock: true,
    rating: 4.5,
    reviews: 280,
    description:
      "Essential daily multivitamin for active individuals. 26 key nutrients.",
    isOnWebsite: false,
    isOnStore: true,
  },
  // Creatine
  {
    id: "cr-1",
    name: "Micronized Creatine Powder",
    brand: "Optimum Nutrition",
    category: "Creatine",
    price: 3800,
    originalPrice: 4800,
    image: "https://m.media-amazon.com/images/I/61mV8YIzL2L._SL1500_.jpg",
    badge: "HOT",
    inStock: true,
    rating: 4.9,
    reviews: 3500,
    description:
      "5g pure creatine monohydrate per serving. Unflavored, mixes easily with any liquid.",
    isOnWebsite: false,
    isOnStore: true,
  },
  {
    id: "cr-2",
    name: "Creatine HMB",
    brand: "MuscleTech",
    category: "Creatine",
    price: 4500,
    originalPrice: 5800,
    image: "https://m.media-amazon.com/images/I/81Y1yC-Bl5L._SL1500_.jpg",
    badge: "SALE",
    inStock: true,
    rating: 4.7,
    reviews: 620,
    description:
      "Creatine monohydrate combined with HMB for maximum strength and muscle building.",
    isOnWebsite: false,
    isOnStore: true,
  },
  // Weight Gainer
  {
    id: "wg-1",
    name: "Serious Mass Weight Gainer",
    brand: "Optimum Nutrition",
    category: "Weight Gainer",
    price: 18500,
    originalPrice: 22000,
    image: "https://m.media-amazon.com/images/I/71H90-V0JyL._SL1500_.jpg",
    badge: "HOT",
    inStock: true,
    rating: 4.8,
    reviews: 2760,
    description:
      "1250 calories per serving. 50g protein, over 250g carbs. The ultimate mass gainer.",
    isOnWebsite: false,
    isOnStore: true,
  },
  {
    id: "wg-2",
    name: "Super Mass Gainer",
    brand: "Dymatize",
    category: "Weight Gainer",
    price: 16800,
    originalPrice: 20000,
    image: "https://m.media-amazon.com/images/I/61KJv3TIaEL._SL1500_.jpg",
    badge: "SALE",
    inStock: true,
    rating: 4.6,
    reviews: 870,
    description:
      "1310 calories, 52g protein per serving. Fortified with vitamins and minerals.",
    isOnWebsite: false,
    isOnStore: true,
  },
  // Shaker Bottle
  {
    id: "sb-1",
    name: "BlenderBottle Classic",
    brand: "MyProtein",
    category: "Shaker Bottle",
    price: 1500,
    originalPrice: 2000,
    image: "https://m.media-amazon.com/images/I/71OBXSDKgjL._SL1500_.jpg",
    badge: "NEW",
    inStock: true,
    rating: 4.8,
    reviews: 5200,
    description:
      "28oz shaker bottle with BlenderBall wire whisk. Leak-proof, dishwasher safe.",
    isOnWebsite: false,
    isOnStore: true,
  },
  {
    id: "sb-2",
    name: "Pro Series Shaker",
    brand: "USN",
    category: "Shaker Bottle",
    price: 1800,
    originalPrice: 2500,
    image: "https://m.media-amazon.com/images/I/61bJGlZtDaL._SL1500_.jpg",
    badge: null,
    inStock: true,
    rating: 4.6,
    reviews: 340,
    description:
      "700ml double-wall shaker with storage compartment. BPA-free plastic.",
    isOnWebsite: false,
    isOnStore: true,
  },
];
